version: "3.8"
services:
  rstudio:
    build: .
    image: maurolepore/ds_terminal:4
    ports:
      - 8787:8787
    environment:
    - PASSWORD=s3cr37
    - ROOT=true
    volumes:
      - .:/home/rstudio/ds.terminal
